---
title: "About Me"
sidebar: false 
---

# Education

-   B.S., Industrial Engineering, Hacettepe University, Turkey, 2020 - ongoing.

# Work Experience

**Office Support Assistant at Hacettepe University (Nov 2022-May 2023)**

	I worked as an assistant alongside department professors as part of a program offered by my school. This work experience helped me develop a sense of responsibility towards my undergraduate studies.

**Customer Support Specialist at Çizgi Studio (July 2022-Sept 2023)**

	I actively participated in the customer-centric aspect of the digital marketing branch within the newly established Çizgi Studio program. During this process, I fostered dynamic relationships with the application's customers and generated effective positive feedback to improve the application. Having such responsibility enabled me to interpret events from different perspectives and optimize them to yield the most efficient results.
	
**Team Leader at Çözene Sor (January 2022-May 2022)**
	
	In the initiative called "Çözene Sor," our goal was to create a suitable forum platform for students preparing for university exams and find teachers and forum developers to be part of this forum. During this process, it was my responsibility to find and select individuals for the team we would create and develop the team's plans. Along with taking on this task, I personally experienced the positive contributions that teamwork can bring to a project by managing and participating in the process.
	
**Sales Representative at Earnado (Dec 2021-May 2022)**
	
	I worked in this company that provides consultancy in social media, where I was responsible for introducing the company to new clients and providing information about the company's services. This process enhanced my sales and social skills.


## Internships

**1.  Engineer Intern at BARKOM GROUP DRILL RIGS & EQUIPMENT INC (August 2023-September 2023)**

  I completed my first internship at Barkom, a company that contributes to state and subcontractor companies seeking raw materials both domestically and internationally with its drilling machines and drilling equipment. During my internship, I actively took on roles within the production and R&D departments, and I gained detailed knowledge about the entire workflow of machines and materials traded with the guidance of expert individuals in the assembly and quality measurement departments. Moreover, in my active role within the R&D department, I saw the many functional contributions of my knowledge about this process.

  To provide a more detailed explanation, I can describe my tasks as follows: During my one-month internship, I actively performed data entry on an Excel file connected to all company computers, documenting the processes that the equipment to be assembled on the machine would go through in the production area. While entering this data, I determined which processes the materials would go through and which lathe machines should be used for these processes. When determining the sequence and location of the processes, I prioritized efficient options that would increase the company's production optimization, considering industrial engineering principles. Additionally, since the Excel file I used would also be used in the company's in-house ERP program, I entered the data for product structures and ensured its accuracy.

  Within the limited time frame of my internship, I processed approximately 1000 rows of data, making significant contributions to listing the company's medium-term equipment procurement, production, and assembly stages.

# Competencies

R, Quarto, Git, Python, Solidworks, AutoCAD, MS Office, Mathlab

# Hobbies
Nature, Fitness, Cooking

# Linkedin
[Serhat Kaya](https://www.linkedin.com/in/serhatkayaa/)